- typed_ast/conversions.py
Python 2 represents negative numeric literals as `Num(n=-NUMBER)`, but Python 3 represents them as `UnaryOp(op=USub(), operand=Num(n=NUMBER))`.  This makes the conversions module actually make this change.
Fixes https://github.com/python/mypy/issues/1788.
> [conversions] Convert negative literals to use unary minus

- ast27/Include/Python-ast.h
- ast27/Parser/Python.asdl
- ast27/Python/Python-ast.c
- ast27/Python/ast.c
Fixes #10 
@gvanrossum @JukkaL @ddfisher 
This is a naive fix. It only checks the first string in concatenation at CST level, for ``b`` or ``B`` prefix and sets the ``has_b`` flag in ``Str`` AST node accordingly.
> Distinguish 'x' and b'x' in Python 2

- ast35/Include/Python-ast.h
- ast35/Parser/Python.asdl
- ast35/Parser/tokenizer.c
- ast35/Python/Python-ast.c
- ast35/Python/ast.c
FWIW, here is the implementation of underscores in numeric literals. I just cherry-picked the necessary parts from the original implementation in Python 3.6 by Georg and Serhiy. This could be useful for mypy.
@ddfisher Please take a look.
> Implement underscores in numeric literals

- ast27/Python/ast.c
> Fix parsing of old style octals in ast27

- ast3/Custom/typed_ast.c
- ast3/Python/ast.c
Fixes #30 
The fix is very straightforward, it looks like it was just an oversight.
(Note that the corresponding Python function is public, so that I also removed ``static`` declaration here)
> Fix segfault on f-string

- ast3/Python/ast.c
> [3.6] Remove unconditional error on async/await name usage

- ast27/Python/ast.c
This lets typed_ast run on debug-mode Python.  I believe this also a minor correctness fix.
> [ast27] Fix PyBytes_AS_STRING being called on unicode objects

- ast27/Python/ast.c
#37 fixed this improperly due to a misreading of the CPython 3.6 source.
> [2.7] Properly fix PyBytes_AS_STRING being called on unicode objects

- ast27/Python/ast.c
- ast3/Python/ast.c
> [2.7, 3.6] Fix invalid read memory errors

- ast3/Python/ast.c
- typed_ast/ast3.py
Python 3.5 introduced three new forms of syntax:
- Coroutines with async/await (PEP 492)
- The '@' operator (PEP 465)
- Additional unpacking generalizations (PEP 448)
This commit adds a version check for the first two, but not the last item.
This commit was originally motivated by https://github.com/python/mypy/issues/2401. I decided to also add a check for the '@' operator because it looked like an easy fix, but didn't add a check for the unpacking generalizations because that seemed harder.
The checks for `async for`, `async with`, and `await` are probably unnecessary because they can only be used inside `async def` anyways, which will always be checked first, but I figured I might as well add them just in case. I can remove them if you want, though, since it probably does incur a …
> Add checks for some 3.5+ only syntax (async/await and the @ operator)

- README.md
- appveyor.yml
- ast27/Custom/typed_ast.c
- ast27/Parser/tokenizer.c
- ast27/Python/ast.c
- ast3/Custom/typed_ast.c
- ast3/Python/ast.c
MSVC 9's weird C99 implementation means that identifiers must be declared at the beginning of a scope. This refactors the code to support that. There are no functional changes to the parsing. I mostly did this out of an interest to see how hard it would be, turns out pretty simple 😄
This should also work for Python 3.3 (I can add it to the build matrix if desired).
> Vs2010 compilation support (Python 3.3/3.4 support)

- README.md
Currently, the Travis badge shows the status of the latest build, regardless of the branch.
For instance, if someone is working on a feature and has broken some tests, the badge in the README on master branch will be red.
This is a followup to https://github.com/python/mypy/pull/3690
> Make Travis badge show build status on master branch

- ast27/Include/Python-ast.h
- ast27/Parser/Python.asdl
- ast27/Python/Python-ast.c
- ast27/Python/ast.c
- ast3/Include/Python-ast.h
- ast3/Parser/Python.asdl
- ast3/Python/Python-ast.c
- ast3/Python/ast.c
This will help experimenting with https://github.com/python/mypy/pull/3648
Currently we preserve only ``b`` string modifier on Python 2, this is a bit arbitrary and for the above mentioned PR we need to keep ``u``. Instead of adding another special-casing I just always preserve all string modifiers in a short string ``kind`` on ``Str`` node, for example:
```python
>>> st = ast3.parse("u'hi'")
>>> st.body[0].value.kind
'u'
```
> Preserve string kind modifiers

- typed_ast/conversions.py
The introduction of string kinds in #49 missed updating the 2to3 visitor
for it. Update the `visit_Str` case to pass `s.kind` to `Str`.
Fixes #66.
> Fix conversions.py2to3 on unicode strings

- typed_ast/ast27.py
- typed_ast/ast3.py
- typed_ast/conversions.py
There is one in the conversions.py2to3 case for a print statement that
suppresses the newline, which causes crashes.
Additionally there are two examples in documentation that leave it out.
> Fix remaining calls to Str without a kind

- typed_ast/__init__.py
The addition of a kind argument to Str should have come with a minor
version bump (since it is backwards incompatible).
The plan is to bump the version, and then to pull the busted 1.1.1.
> Bump version to 1.2.0-dev

- .gitignore
- .travis.yml
- ast3/tests/test_basics.py
This adds some very basic tests for ast3, and modifies .travis.yml to run them (while still also building the Linux wheels). The key here is getting some infrastructure going, we can elaborate in subsequent PRs.
> Add some tests

- ast3/tests/test_basics.py
I found out that I'd accidentally left this out from the update-37 branch.
Note that this does not verify the bugs fixed between release 1.1.1 and 1.2.0.
> Verify that Str objects have a kind argument/attribute

- ast3/Include/Python-ast.h
- ast3/Parser/Python.asdl
- ast3/Python/Python-ast.c
- ast3/Python/ast.c
- ast3/tests/test_basics.py
- typed_ast/conversions.py
For consistency with the kind field in Str.
Fixes #74.
The interesting changes are to `ast.c`.
> Add a kind field to Bytes as well

- ast3/Parser/tokenizer.c
- ast3/tests/test_basics.py
It was caused by a somewhat gnarly tokenizer issue.
Fixes #76.
> Fix await in functions with type comments

- ast3/Custom/typed_ast.c
- ast3/Python/ast.c
- ast3/tests/test_basics.py
typed-ast has (for a while) done f-string weirdly, essentially parsing
the f string contents twice. This was dodgy but harmless until a 3.7
change tweaked the string that was being used for the second parse to
be enclosed by braces, which is causing typed_ast to think that every
value in an f-string is a set.
Restore things to working like cpython.
> Fix f-string parsing to not think everything is a set

- ast3/Parser/parsetok.c
- ast3/Python/ast.c
Echoes https://github.com/python/cpython/pull/11728 (they were found
by the CPython refleak detector, see
https://bugs.python.org/issue35879).
> Fix memory leaks caused by type comment parsing

- ast3/Python/ast.c
This is mostly cribbed from https://github.com/python/cpython/pull/11645,
though it also adds a new error check to new_type_comment itself.
> Check NEW_TYPE_COMMENT calls for failure

- MANIFEST.in
- setup.py
Patch from the Debian package for typed_ast, we use this to run the tests at build time and post-install. With this PR `typed_ast` users can also run the tests post-install and from any directory:
`python -m pytest --pyargs typed_ast`
> Distribute the tests

- ast3/Python/ast.c
The patch is taken from a commit to the CPython repo with the message:
> bpo-36495: Fix two out-of-bounds array reads (GH-12641)
> 
> Research and fix by @bradlarsen.
Some code I have triggered segmentation fault when I run pylint on it. With this patch, I don't get segmentation fault anylonger.
Backtrace from GDB:
#0  0x00001ff4e48a883b in ast_for_arguments () from $HOME/.local/lib/python3.6/site-packages/typed_ast/_ast3.so
#1  0x00001ff4e48ac4c0 in ast_for_funcdef_impl () from $HOME/.local/lib/python3.6/site-packages/typed_ast/_ast3.so
#2  0x00001ff4e48ac315 in ast_for_suite () from $HOME/.local/lib/python3.6/site-packages/typed_ast/_ast3.so
#3  0x00001ff4e48abd1e in ast_for_classdef () from $HOME/.local/lib/python3.6/site-packages/typed_ast/_ast3.so
#4  0x00001ff4e48a22c7 in …
> Fix two out-of-bounds array reads

- .travis.yml
- ast27/Include/pgenheaders.h
- ast3/Include/pgenheaders.h
It turns out we don't need anything from it anyways other than the
import of Python.h. Since some of the files that import it are
generated, I added dummy pgenheaders.h instead of changing the
importing files.
> Don't rely on Python's pgenheaders.h

- typed_ast/ast27.py
> Don't reference basestring -- this is always run in Python 3!

- .gitattributes
- ast27/Include/Python-ast.h
- ast27/Parser/Python.asdl
- ast27/Parser/parsetok.c
- ast27/Parser/tokenizer.c
- ast27/Python/Python-ast.c
- ast27/Python/ast.c
- ast3/Include/Python-ast.h
- ast3/Parser/Python.asdl
- ast3/Parser/parsetok.c
- ast3/Parser/tokenizer.c
- ast3/Python/Python-ast.c
- ast3/Python/ast.c
- ast3/tests/test_basics.py
- tools/update_ast27_asdl
This is to allow things like `# type: ignore[E1000]`.
Essentially a backport of GH-13238, GH-13479, and GH-13504 from cpython.
> Support text appearing after "# type: ignore"

- ast27/Custom/typed_ast.c
- ast3/Custom/typed_ast.c
- ast3/Include/compile-ast3.h
- ast3/Python/ast.c
Two things to do this:
* Use a version check (instead of a macro definedness check) to determine
whether to emulate _PyObject_FastCall
* Use the graminit.h versions of Py_func_type_input and friends
directly instead of defining them in a compile-ast3.h, since
Py_func_type_input showed back up in a public header with a
different value in 3.8 and caused warnings.
> Fix compilation on Python 3.8

- ast3/Python/ast.c
https://github.com/python/cpython/pull/16013 / https://github.com/python/cpython/commit/3a4f66707e824ef3a8384827590ebaa6ca463dc0
removed two arguments from _PyBytes_DecodeEscape .
This calls _PyBytes_DecodeEscape with the new signature if the minor version is 9 or greater.
Followed the convention of only checking minor versions from earlier in the code.
> FIX: build on cpython master branch

- .travis.yml
https://www.python.org/download/pre-releases/
Also, address Travis build config validation issues:
* `skip_cleanup` is now deprecated https://blog.travis-ci.com/2019-08-27-deployment-tooling-dpl-v2-preview-release
> Travis CI: Test Python 3.9 release candidate 1

- appveyor.yml
Not sure if this will works, 3.9 is not yet listed on the indicated page.
Might fix #146 and then also will fix https://github.com/python/mypy/issues/9488
> Add Python 3.9 for Windows

- ast27/Parser/parser.c
- ast3/Parser/parser.c
> Remove reference to PyNode_ListTree for Python 3.10

- ast27/Include/asdl.h
- ast27/Python/asdl.c
- ast27/Python/ast.c
Fixes #151 and (probably) fixes #139
Linking shenanigans caused ast27 to link against Python's `asdl.c`, instead of `ast27/Python/asdl.c`. Python's `asdl.c` uses `Py_ssize_t` for `asdl_seq`'s size whereas `ast27/Python/asdl.c` uses `int`. This means we were interpreting memory differently in `asdl.c` and `ast.c`. On 64-bit big-endian systems, this caused us to misplace `asdl.c`'s writes to `asdl_seq->size`, since `Py_ssize_t` is eight bytes, but `int` is four. The fix mirrors what we do in ast3, that is, manually namespace definitions to avoid linking conflicts.
> ast27: prefix exported symbols

- ast27/Parser/tokenizer.c
- ast27/Python/ast.c
It seems that pydebug.h and pyarena.h were moved from /Include/ to /Include/cpython/ in the latest 3.10 alpha (a6).
> Allow compilation on python 3.10.0a6

- ast27/Include/asdl.h
- ast27/Include/pyarena.h
- ast27/Include/pycore_pyarena.h
- ast3/Include/asdl.h
- ast3/Include/pyarena.h
- ast3/Include/pycore_pyarena.h
PyArena was removed from the public api in https://github.com/python/cpython/pull/25007
This commit adds two new files:
* pycore_pyarena.h: Taken from the cpython source code with minimal
changes
* pyarena.h: Maps the new, underscored function names to the old
function names, allowing the code to work on both python 3.10 and
older versions
> Fix compilation on python 3.10.0a7

- release_process.md
What we really should do is use cibuildwheel, like we do for mypy.
> Improve release process documentation

- ast3/Python/ast.c
Fixes https://github.com/python/typed_ast/issues/169
~I have tested this on 3.9.8, 3.9.7 and 3.10.0 only.~ The CI tested this more.
> Define _PyUnicode_DecodeUnicodeEscape even on Python 3.6+

- README.md
- setup.py
> Recommend ast on Python 3.8+

- ast27/Python/mystrtoul.c
Copy _PyLong_DigitValue table from Python 3.10 as "digitvalue" in
ast27/Python/mystrtoul.c. The symbol has been removed from the public
Python 3.11 C API.
> Fix #167: Port ast27 to Python 3.11

- .github/workflows/build.yml
- ast3/Parser/tokenizer.c
The compilation error on master is:
```
ast3/Parser/tokenizer.c:1991:10: error: implicit declaration of function '_Py_dup' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
fd = _Py_dup(fd);
^
1 error generated.
```
Probably as a result of https://github.com/python/cpython/pull/30484
Just declaring it seems to fix things.
Add a (slightly) hacky way of testing Python 3.11 in CI prior to manylinux / cibuildwheel support.
> Fix Python 3.11 support

- ast27/Include/compile.h
As of https://github.com/python/cpython/pull/32385 the header
code.h is private but directly included into Python.h
> BLD: do not include now private header files

- .github/workflows/build.yml
- Upgrade GitHub Action versions.
- Employ cibuildwheel action instead of manual setup.
- This upgrade also changes the manylinux image to **manylinux2014** (2010 is EOL and has no 3.11 support).
> Upgrade cibuildwheel - Add Python 3.11 & musllinux
